<?xml version="1.0" ?>
<testsuite errors="1" failures="1" name="fts.stable_topology_fts.StableTopFTS" skip="0" tests="1" time="370.230571032">
	<testcase name="fts.stable_topology_fts.StableTopFTS.index_query_custom_mapping,num_queries:100,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-19-Jul-11_13-14-54/test_1,GROUP:P0,index_type:scorch,compare_es:True,cluster:D:F,items:1000,fts_quota:750,conf_file:test.conf,num_nodes:2,cluster_name:test,cm_id:9,ini:test.ini,case_number:1,custom_map:True,spec:test,disable_HTP:True" time="370.230571032">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/fts/stable_topology_fts.py&quot;, line 546, in index_query_custom_mapping\n    self.run_query_and_compare(index, n1ql_executor=n1ql_executor)\n  File &quot;pytests/fts/fts_base.py&quot;, line 4230, in run_query_and_compare\n    failed_queries))\nAssertionError: 100 out of 100 queries failed! - [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]\n']</error>
	</testcase>
</testsuite>
