<?xml version="1.0" ?>
<testsuite errors="1" failures="1" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="1" time="47.96524500846863">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_comp_ops,test_name:fts_index_exists,GROUP:PS,get-logs:False,stop-on-failure:False,doc-per-day:6,bucket_size:200,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,custom_map:True,get-cbcollect-info:False,disable_HTP:True,cluster:D+F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,cm_id:1,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,num_nodes:1,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-Apr-23_11-42-44/test_1" time="47.96524500846863">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 198, in test_flex_single_typemapping_comp_ops\n    self.generate_random_queries(fts_index)\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 129, in generate_random_queries\n    fields=fts_index.smart_query_fields)\n  File &quot;pytests/fts/random_query_generator/rand_query_gen.py&quot;, line 914, in __init__\n    self.check_for_array_fields(fields)\n  File &quot;pytests/fts/random_query_generator/rand_query_gen.py&quot;, line 931, in check_for_array_fields\n    self.fields[\'str\'].remove(array_field)\nValueError: list.remove(x): x not in list\n']</error>
	</testcase>
</testsuite>
