<?xml version="1.0" ?>
<testsuite errors="1" failures="1" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="1" time="98.70898604393005">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,GROUP:PS,get-logs:False,stop-on-failure:False,doc-per-day:6,bucket_size:200,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,custom_map:True,get-cbcollect-info:False,disable_HTP:True,cluster:D+F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,num_nodes:4,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-Apr-29_17-45-04/test_1" time="98.70898604393005">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 315, in test_flex_single_typemapping_partial_sargability\n    self.generate_random_queries()\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 141, in generate_random_queries\n    fields=fields)\n  File &quot;pytests/fts/random_query_generator/rand_query_gen.py&quot;, line 921, in __init__\n    self.check_for_array_fields_remove_type(self.fields)\n  File &quot;pytests/fts/random_query_generator/rand_query_gen.py&quot;, line 939, in check_for_array_fields_remove_type\n    fields[\'text\'].remove(text_field)\nValueError: list.remove(x): x not in list\n']</error>
	</testcase>
</testsuite>
