<?xml version="1.0" ?>
<testsuite errors="1" failures="1" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="1" time="65.25347208976746">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_comp_ops,test_name:fts_index_exists,GROUP:PS,get-logs:False,stop-on-failure:False,doc-per-day:6,bucket_size:200,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,custom_map:True,get-cbcollect-info:False,disable_HTP:True,cluster:D+F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,cm_id:3,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,num_nodes:1,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-Apr-23_14-08-31/test_1" time="65.25347208976746">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 204, in test_flex_single_typemapping_comp_ops\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [5, 6, 7, 8, 9, 14] or flex query and gsi query results not matching: [1, 2, 3, 4, 39, 40, 41, 42, 43]\n']</error>
	</testcase>
</testsuite>
