<?xml version="1.0" ?>
<testsuite errors="1" failures="1" name="fts.stable_topology_fts.StableTopFTS" skip="0" tests="1" time="11.9999320507">
	<testcase name="fts.stable_topology_fts.StableTopFTS.test_sort_geo_query,num_queries:100,skip-cleanup:True,compare_es:True,items:1000,conf_file:test.conf,num_nodes:1,cluster_name:test,cluster:D+F,ini:test.ini,case_number:1,fail-on-errors:False,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-19-Jun-12_16-14-44/test_1,spec:test" time="11.9999320507">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/fts/stable_topology_fts.py&quot;, line 21, in setUp\n    super(StableTopFTS, self).setUp()\n  File &quot;pytests/fts/fts_base.py&quot;, line 3045, in setUp\n    self.__init_parameters()\n  File &quot;pytests/fts/fts_base.py&quot;, line 3284, in __init_parameters\n    self.es.restart_es()\n  File &quot;pytests/fts/es_base.py&quot;, line 239, in restart_es\n    self.__log.info(&quot;Restarted ES server %s successfully&quot; % self.ip)\nAttributeError: \'ElasticSearchBase\' object has no attribute \'ip\'\n']</error>
	</testcase>
</testsuite>
