<?xml version="1.0" ?>
<testsuite errors="1" failures="1" name="tuqquery.n1ql_fts_integration.N1qlFTSIntegrationTest" skip="0" tests="2" time="479.519227982">
	<testcase name="tuqquery.n1ql_fts_integration.N1qlFTSIntegrationTest.test_mixed_cluster,doc-per-day:1,GROUP:P1,spec:test,reset_services:True,num_nodes:3,cluster_name:test,services_init:kv:index:n1ql-kv-index:n1ql:fts,conf_file:test.conf,case_number:1,get-logs:False,stop-on-failure:False,scan_consistency:NOT_BOUNDED,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-19-Aug-12_15-13-59/test_1,bucket_size:200,nodes_init:3,ini:test.ini" time="363.909435987"/>
	<testcase name="tuqquery.n1ql_fts_integration.N1qlFTSIntegrationTest.test_n1ql_syntax,doc-per-day:1,GROUP:P1,case_number:2,spec:test,reset_services:True,num_nodes:3,cluster_name:test,services_init:kv:index:n1ql-index:n1ql:fts,conf_file:test.conf,test_name:select_term,get-logs:False,stop-on-failure:False,scan_consistency:NOT_BOUNDED,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-19-Aug-12_15-13-59/test_2,bucket_size:200,nodes_init:2,ini:test.ini" time="115.609791994">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/n1ql_fts_integration.py&quot;, line 393, in test_n1ql_syntax\n    self.assertEquals(test_result, True, &quot;Node &quot;+str(node)+&quot; test &quot;+test_name+&quot; is failed.&quot;)\nAssertionError: Node ip:192.168.10.13 port:8091 ssh_username:root test select_term is failed.\n']</error>
	</testcase>
</testsuite>
