<?xml version="1.0" ?>
<testsuite errors="2" failures="2" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="2" time="718.4307508468628">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,GROUP:P1,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,custom_map:True,cluster:D+F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_gsi_query,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:1,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-01_15-03-13/test_1" time="394.4920518398285">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 439, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [67, 68, 70, 74, 75, 76] or flex query and gsi query results not matching: [8, 16, 17, 19, 22, 23, 38, 43, 44, 45, 52, 55, 66]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,GROUP:P1,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,custom_map:True,cluster:D+F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:1,case_number:2,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-01_15-03-13/test_2" time="323.9386990070343">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 439, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [67, 68, 70, 74, 75, 76] or flex query and gsi query results not matching: [8, 19, 22, 23, 38, 42, 43, 44, 45, 52, 55, 66, 71, 72, 73]\n']</error>
	</testcase>
</testsuite>
