<?xml version="1.0" ?>
<testsuite errors="2" failures="2" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="2" time="347.0527617931366">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,custom_map:True,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:4,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-05_15-13-49/test_1" time="178.56575274467468">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 393, in test_flex_single_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [16, 29] or flex query and gsi query results not matching: [1, 2, 3, 4, 5, 7, 9, 23, 24, 25, 26, 28, 31, 37, 38, 39, 40, 41, 42, 44, 45, 46, 52, 53, 54, 55]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_multi_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,nodes_init:3,custom_map:True,flex_dataset:all,doc_maps:2,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:4,case_number:2,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-05_15-13-49/test_2" time="168.4870090484619">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 411, in test_flex_multi_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
</testsuite>
