<?xml version="1.0" ?>
<testsuite errors="1" failures="1" name="tuqquery.n1ql_fts_integration.N1qlFTSIntegrationTest" skip="0" tests="1" time="403.175245047">
	<testcase name="tuqquery.n1ql_fts_integration.N1qlFTSIntegrationTest.test_mixed_cluster,doc-per-day:1,GROUP:P1,spec:test,reset_services:True,num_nodes:3,cluster_name:test,services_init:kv:index:n1ql-kv-index:n1ql:fts,conf_file:test.conf,case_number:1,get-logs:False,stop-on-failure:False,scan_consistency:NOT_BOUNDED,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-19-Aug-12_14-10-45/test_1,bucket_size:200,nodes_init:3,ini:test.ini" time="403.175245047">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/n1ql_fts_integration.py&quot;, line 376, in test_mixed_cluster\n    self.assertEquals(test_result, True, &quot;Node &quot; + str(node) + &quot; test is failed.&quot;)\nAssertionError: Node ip:192.168.10.12 port:8091 ssh_username:root test is failed.\n']</error>
	</testcase>
</testsuite>
