<?xml version="1.0" ?>
<testsuite errors="88" failures="88" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="88" time="18882.625553369522">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_1" time="295.10206508636475">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_gsi_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:2,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_2" time="168.7684450149536">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:3,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_3" time="166.01574683189392">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:4,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_4" time="165.1754379272461">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:1,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:5,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_5" time="170.23079013824463">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:1,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:6,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_6" time="165.7826018333435">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:2,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:7,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_7" time="168.38914704322815">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:2,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:8,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_8" time="170.23668694496155">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:3,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:9,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_9" time="167.49350571632385">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:3,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:10,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_10" time="171.18669986724854">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:4,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:11,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_11" time="170.52368879318237">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:4,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:12,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_12" time="166.6819770336151">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:5,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:13,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_13" time="171.611172914505">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:5,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:14,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_14" time="167.53306913375854">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:15,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_15" time="195.50563716888428">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 47, 48, 49, 50, 51]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_gsi_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:16,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_16" time="198.93620467185974">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 47, 48, 49, 50, 51]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:17,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_17" time="190.39250993728638">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:18,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_18" time="194.58032202720642">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:1,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:19,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_19" time="194.3132131099701">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:1,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:20,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_20" time="193.28993725776672">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 44, 47, 48, 49, 50, 51, 53, 55]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:2,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:21,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_21" time="197.8018810749054">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:2,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:22,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_22" time="205.71790313720703">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 43, 47, 48, 49, 50, 51, 52, 54, 55]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:3,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:23,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_23" time="194.60968232154846">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:3,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:24,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_24" time="192.81625819206238">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 43, 44, 47, 48, 49, 50, 51]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:4,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:25,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_25" time="192.70186686515808">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:4,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:26,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_26" time="194.88816499710083">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 47, 48, 49, 50, 51, 54]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:5,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:27,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_27" time="203.77817916870117">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [31, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 75, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 42, 43, 44, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:5,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:28,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_28" time="199.71843314170837">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_partial_sargability\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 47, 48, 49, 50, 51, 54, 55, 56]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:29,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_29" time="410.89901900291443">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 76] or flex query and gsi query results not matching: [3, 4, 5, 6, 7, 37, 39, 40, 47, 48, 49, 50, 51, 52]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_gsi_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:30,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_30" time="406.99165391921997">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [8, 11, 12, 13, 16, 17, 21, 22, 24, 28, 30, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 73, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:31,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_31" time="387.83883118629456">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:32,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_32" time="733.8869943618774">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:1,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:33,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_33" time="387.539546251297">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:1,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:34,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_34" time="399.9898769855499">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [8, 11, 12, 13, 16, 17, 21, 22, 24, 28, 30, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 73, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:2,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:35,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_35" time="391.7150089740753">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:2,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:36,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_36" time="404.52055191993713">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [8, 11, 12, 13, 16, 17, 21, 22, 24, 28, 30, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 73, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:3,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:37,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_37" time="392.3160047531128">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:3,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:38,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_38" time="411.517902135849">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [8, 11, 12, 13, 16, 17, 21, 22, 24, 28, 30, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 73, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:4,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:39,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_39" time="392.69232296943665">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:4,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:40,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_40" time="405.9502799510956">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [8, 11, 12, 13, 16, 17, 21, 22, 24, 28, 30, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 73, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:5,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:41,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_41" time="392.01231694221497">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:5,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:42,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_42" time="405.56718492507935">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 445, in test_flex_single_typemapping_2_fts_indexes\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [8, 11, 12, 13, 16, 17, 21, 22, 24, 28, 30, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 73, 75, 76] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:43,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_43" time="153.20896887779236">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:1,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:44,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_44" time="150.57558012008667">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:2,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:45,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_45" time="152.77944207191467">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:3,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:46,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_46" time="154.6220622062683">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:4,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:47,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_47" time="142.5468807220459">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:5,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:48,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_48" time="140.96079778671265">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:6,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:49,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_49" time="196.07441186904907">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:7,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:50,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_50" time="153.06766819953918">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:8,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:51,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_51" time="144.2034330368042">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:9,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:52,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_52" time="155.43033909797668">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:10,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:53,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_53" time="153.60686826705933">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:11,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:54,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_54" time="164.89079022407532">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:12,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:55,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_55" time="145.58226203918457">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:13,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:56,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_56" time="160.07209706306458">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:14,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:57,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_57" time="166.62218689918518">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:15,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:58,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_58" time="146.339252948761">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:16,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:59,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_59" time="186.0557827949524">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:17,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:60,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_60" time="178.49234628677368">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:18,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:61,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_61" time="179.54169082641602">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,cm_id:19,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:62,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_62" time="168.97086596488953">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:63,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_63" time="170.97884798049927">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:1,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:64,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_64" time="156.3091230392456">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:2,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:65,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_65" time="167.03622198104858">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:3,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:66,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_66" time="170.58730506896973">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:4,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:67,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_67" time="149.76596307754517">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:5,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:68,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_68" time="156.6145887374878">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:6,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:69,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_69" time="211.17414498329163">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:7,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:70,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_70" time="158.69198989868164">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:8,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:71,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_71" time="165.6311321258545">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:9,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:72,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_72" time="177.1216480731964">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:10,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:73,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_73" time="197.59886193275452">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:11,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:74,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_74" time="169.92163801193237">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:12,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:75,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_75" time="169.55404996871948">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:13,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:76,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_76" time="223.51722598075867">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:14,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:77,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_77" time="190.930410861969">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:15,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:78,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_78" time="189.80865383148193">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:16,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:79,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_79" time="159.1930251121521">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:17,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:80,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_80" time="190.97067999839783">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:18,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:81,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_81" time="177.45799612998962">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,cm_id:19,nodes_init:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:82,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_82" time="177.97715497016907">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:83,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_83" time="165.89628386497498">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 369, in test_flex_single_typemapping\n    if not self.is_index_present(&quot;default&quot;, &quot;primary_gsi_index&quot;):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 93, in create_index\n    self.fail(&quot;FTS indexing did not complete. FTS index count : {0}, Bucket count : {1}&quot;.format(indexed_doc_count, doc_count))\nAssertionError: FTS indexing did not complete. FTS index count : 497, Bucket count : 1000\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:1,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:84,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_84" time="164.3065152168274">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 369, in test_flex_single_typemapping\n    if not self.is_index_present(&quot;default&quot;, &quot;primary_gsi_index&quot;):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 93, in create_index\n    self.fail(&quot;FTS indexing did not complete. FTS index count : {0}, Bucket count : {1}&quot;.format(indexed_doc_count, doc_count))\nAssertionError: FTS indexing did not complete. FTS index count : 589, Bucket count : 1000\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:2,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:85,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_85" time="177.43029594421387">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 379, in test_flex_single_typemapping\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:3,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:86,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_86" time="164.63062572479248">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 369, in test_flex_single_typemapping\n    if not self.is_index_present(&quot;default&quot;, &quot;primary_gsi_index&quot;):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 93, in create_index\n    self.fail(&quot;FTS indexing did not complete. FTS index count : {0}, Bucket count : {1}&quot;.format(indexed_doc_count, doc_count))\nAssertionError: FTS indexing did not complete. FTS index count : 751, Bucket count : 1000\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:4,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:87,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_87" time="166.4465410709381">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 369, in test_flex_single_typemapping\n    if not self.is_index_present(&quot;default&quot;, &quot;primary_gsi_index&quot;):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 93, in create_index\n    self.fail(&quot;FTS indexing did not complete. FTS index count : {0}, Bucket count : {1}&quot;.format(indexed_doc_count, doc_count))\nAssertionError: FTS indexing did not complete. FTS index count : 222, Bucket count : 1000\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_query,cm_id:5,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:88,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-33-38/test_88" time="162.21218085289001">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 369, in test_flex_single_typemapping\n    if not self.is_index_present(&quot;default&quot;, &quot;primary_gsi_index&quot;):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 93, in create_index\n    self.fail(&quot;FTS indexing did not complete. FTS index count : {0}, Bucket count : {1}&quot;.format(indexed_doc_count, doc_count))\nAssertionError: FTS indexing did not complete. FTS index count : 896, Bucket count : 1000\n']</error>
	</testcase>
</testsuite>
