<?xml version="1.0" ?>
<testsuite errors="1" failures="1" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="1" time="108.21271705627441">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,test_name:fts_index_exists,GROUP:PS,get-logs:False,stop-on-failure:False,doc-per-day:6,bucket_size:200,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,custom_map:True,get-cbcollect-info:False,disable_HTP:True,cluster:D+F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,num_nodes:4,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-Apr-28_15-17-47/test_1" time="108.21271705627441">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 306, in test_flex_single_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [31, 34, 41, 42, 43, 44, 45] or required index not found in the query resonse: [30, 33, 53] or flex query and gsi query results not matching: [5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 26, 27, 28, 29, 37, 38, 39, 40, 56]\n']</error>
	</testcase>
</testsuite>
