<?xml version="1.0" ?>
<testsuite errors="1" failures="1" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="2" time="371.0893609523773">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,custom_map:True,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-05_18-04-18/test_1" time="171.07898688316345">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 394, in test_flex_single_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [38, 41] or flex query and gsi query results not matching: []\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_multi_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_query,nodes_init:3,custom_map:True,flex_dataset:all,doc_maps:2,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:2,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-05_18-04-18/test_2" time="200.01037406921387"/>
</testsuite>
