<?xml version="1.0" ?>
<testsuite errors="2" failures="2" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="3" time="1360.1391739845276">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_multi_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,nodes_init:3,custom_map:True,flex_dataset:all,doc_maps:2,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-06_21-00-22/test_1" time="444.90744400024414">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 415, in test_flex_multi_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [1, 4, 7, 12, 13, 18, 24, 33, 36, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 82, 85, 88, 93, 94, 102, 111, 112, 113, 114, 115, 116, 117, 120, 121, 122, 123, 124, 125, 126, 127, 132, 133, 138, 139, 150, 153, 156, 159, 165, 174, 177, 180, 183] or flex query and gsi query results not matching: [3, 6, 9, 15, 21, 27, 30, 39, 84, 87, 90, 96, 99, 105, 108, 129, 135, 141, 144, 147, 171]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,custom_map:True,,nodes_init:3,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:2,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-06_21-00-22/test_2" time="203.7744779586792">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 396, in test_flex_single_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [39, 40, 42] or flex query and gsi query results not matching: [28, 29, 30, 31, 32, 48, 51, 58, 59, 60, 61]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,nodes_init:3,flex_dataset:default,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:3,case_number:3,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-06_21-00-22/test_3" time="711.4572520256042"/>
</testsuite>
