<?xml version="1.0" ?>
<testsuite errors="1" failures="1" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="1" time="44.79618215560913">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_comp_ops,test_name:fts_index_exists,GROUP:PS,get-logs:False,stop-on-failure:False,doc-per-day:6,bucket_size:200,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,custom_map:False,get-cbcollect-info:False,disable_HTP:True,cluster:D+F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,dataset:wiki,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,num_nodes:2,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-Apr-22_15-16-04/test_1" time="44.79618215560913">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 22, in setUp\n    super(FlexIndexTests, self).setUp()\n  File &quot;pytests/tuqquery/tuq.py&quot;, line 89, in setUp\n    self.gens_load = self.gen_docs(self.docs_per_day)\n  File &quot;pytests/tuqquery/tuq.py&quot;, line 788, in gen_docs\n    self.fail(&quot;There is no dataset %s, please enter a valid one&quot; % self.dataset)\nAssertionError: There is no dataset wiki, please enter a valid one\n']</error>
	</testcase>
</testsuite>
