<?xml version="1.0" ?>
<testsuite errors="2" failures="2" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="2" time="407.3581929206848">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:1,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-15-19/test_1" time="251.8210370540619">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 397, in test_flex_default_typemapping\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [9, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 67, 68, 69, 75] or flex query and gsi query results not matching: [1, 3, 4, 5, 6, 7, 8, 10, 25, 26, 27, 34, 35, 36, 40, 41, 42, 44, 45, 73]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_default_typemapping,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,bucket_size:200,cluster:D,D+F,F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_gsi_query,ini:test.ini,cluster_name:test,spec:flex_index_sartgability,conf_file:conf/tuq/flex_index_sartgability.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:1,case_number:2,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-02_16-15-19/test_2" time="155.53715586662292">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 387, in test_flex_default_typemapping\n    index_name=&quot;default_index&quot;)\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 93, in create_index\n    self.fail(&quot;FTS indexing did not complete. FTS index count : {0}, Bucket count : {1}&quot;.format(indexed_doc_count, doc_count))\nAssertionError: FTS indexing did not complete. FTS index count : 833, Bucket count : 1000\n']</error>
	</testcase>
</testsuite>
