<?xml version="1.0" ?>
<testsuite errors="2" failures="2" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="2" time="372.8422939777374">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,GROUP:P1,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,custom_map:True,cluster:D+F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:True,flex_query_option:flex_use_fts_gsi_query,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:1,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-01_14-20-07/test_1" time="351.968505859375">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 442, in test_flex_single_typemapping_2_fts_indexes\n    .format(failed_to_run_query, not_found_index_in_response, result_mismatch))\nAssertionError: Found queries not runnable: [] or required index not found in the query resonse: [34, 39, 41, 42] or flex query and gsi query results not matching: [3, 4, 6, 7, 9, 10, 16, 18, 19, 20, 26, 27, 28, 29, 36, 58, 64, 67, 69, 70, 71, 75]\n']</error>
	</testcase>
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_2_fts_indexes,GROUP:P1,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,custom_map:True,cluster:D+F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,flex_query_option:flex_use_fts_gsi_query,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,get-cbcollect-info:False,get-logs:False,stop-on-failure:False,num_nodes:1,case_number:2,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-May-01_14-20-07/test_2" time="20.873788118362427">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 418, in test_flex_single_typemapping_2_fts_indexes\n    self._load_emp_dataset(end=self.num_items)\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 51, in _load_emp_dataset\n    self.cluster.bucket_flush(self.master)\n  File &quot;lib/couchbase_helper/cluster.py&quot;, line 1141, in bucket_flush\n    return _task.result(timeout)\n  File &quot;lib/tasks/future.py&quot;, line 160, in result\n    return self.__get_result()\n  File &quot;lib/tasks/future.py&quot;, line 112, in __get_result\n    raise self._exception\n  File &quot;lib/tasks/task.py&quot;, line 4231, in execute\n    if rest.flush_bucket(self.bucket):\n  File &quot;lib/membase/api/rest_client.py&quot;, line 3417, in flush_bucket\n    raise BucketFlushFailed(self.ip, bucket_name)\nmembase.api.exception.BucketFlushFailed: unable to flush bucket default on the host @ 172.23.121.68\n']</error>
	</testcase>
</testsuite>
